### ISSUE TITLE
No auto-complete for 'Ivy'

### ISSUE THREAD

**Issue by jdrever** [jdrever/openwild#12]
@tomdrever any idea why Ivy returns 10 autocomplete records but none of them are just Ivy ? Or why there are multiple name/language records returned e.g Bwyd Hwyaid, Dail Meillion y Dwfr, Ivy-Leaved Duckweed, Ivy-leaved Duckweed, Llinad Dail Eiddew, Llinad Eiddew, Llinad y Dŵr Eiddewddail, Llinhad y Dŵr Eiddewddail

**Comment by tomdrever** [comment]
Pushed a small change that should fix this

**Comment by jdrever** [comment]
@tomdrever yes can see this is much better. ty.
