### ISSUE TITLE
Page 16 - species in a square list shows "no records" even if API returns data unless name/plant options are changed to refresh

### ISSUE THREAD

**Issue by jdrever** [jdrever/openwild#24]

**Comment by jdrever** [comment]
@tomdrever sorry to be a pain but again, can't replicate, can you send a screenshot of this happening?  Wondering if caused by NBN downtime without proper error appearing?

**Comment by tomdrever** [comment]
I can't replicate this either on live or local site so was probably related to NBN issues yeah
