### ISSUE TITLE
test current development version against Shropbot testing plan

### ISSUE THREAD

**Issue by jdrever** [jdrever/openwild#3]

**Comment by tomdrever** [comment]
## Testing plan comments

Page 1 - autocomplete is present in search result - should test this too?
Page 2 - give examples for common name search
Page 3 - some issues with going back / pressing back button from list of species in county - can fill in url with incorrect details
(search for bryophyte by common name -> click on scientific name in list -> click back to search -> searchs for scientific name, only plants)
Page 4 - list species on empty search box doesn't work

-- autocomplete for common name gives some weird long names sometimes --

Page 5 - clicking page tabs on species list changes title to scientific name 
Page 7 - species name in title changes clicking from species list to species list in site

-- If NBN API is down just says "No records could be found matching those criteria." --

Page 10 - sites name autocomplete
Page 11 - "both" option for species at a site returns no records

Page 13 - going back from single species in square from single species in site goes to species in county

Page 16 - species in a square list shows "no records" even if API returns data unless name/plant options are changed to refresh
